spring:
  cache:
    cache-names: js
server:
  port: 2907
http:
  proxyHost:
  proxyPort:
logging:
  file: log/privacy-proxy.log
  level:
    ROOT: INFO
    de.tk.opensource.privacyproxy: INFO
    de.tk.opensource.privacyproxy.controller: DEBUG
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
---
spring:
  profiles: dev
assets:
  fileLocation: 'C:\SPU\Temp'
example:
  scripts:
    endpoints:
      - remoteUrl: 'https://code.jquery.com/jquery-3.3.1.js'
        filename: 'jquery.js'
    update: true
    interval: '0 */2 * * * ?'
  routing:
    endpoint: 'https://tracking.example.de/dev/piwik.php'
    environment: dev
logging:
  level:
    de.tk.opensource.privacyproxy: DEBUG
---
spring:
  profiles: qa
assets:
  fileLocation: 'tmp/privacy-proxy'
example:
  scripts:
    endpoints:
      - remoteUrl: 'https://code.jquery.com/jquery-3.3.1.min.js'
        filename: 'jquery.js'
    interval: '0 */2 * * * ?'
  routing:
    endpoint: https://tracking.example.de/qa/piwik.php
    environment: qa
---
spring:
  profiles: prod
assets:
  fileLocation: 'tmp/privacy-proxy'
example:
  scripts:
    endpoints:
      - remoteUrl: 'https://code.jquery.com/jquery-3.3.1.min.js'
        filename: 'jquery.js'
    interval: '0 */30 * * * ?'
  routing:
    endpoint: 'https://tracking.example.de/prod/piwik.php'
    environment: prod
