spring:
  cache:
    cache-names: js, ttf
server:
  port: 2907
logging:
  file: log/privacy-proxy.log
  level:
    ROOT: INFO
    de.tk.opensource.privacyproxy: INFO
    de.tk.opensource.privacyproxy.controller: DEBUG
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
---
spring:
  profiles: tk-proxy
http:
  proxyHost: proxy.tk-inline.de
  proxyPort: 8080
---
spring:
  profiles: dev
assets:
  fileLocation: 'C:\SPU\Temp'
google:
  fonts:
    endpoints:
      - remoteUrl: 'https://fonts.google.com/download?family=Roboto'
        filename: 'roboto.zip'
      - remoteUrl: 'https://fonts.google.com/download?family=Open+Sans'
        filename: 'open-sans.zip'
    update: true
    interval: '0 */2 * * * ?'
example:
  scripts:
    endpoints:
      - remoteUrl: 'https://code.jquery.com/jquery-3.3.1.js'
        filename: 'jquery.js'
    update: true
    interval: '0 */2 * * * ?'
  routing:
    endpoint: 'https://tracking.example.de/dev/piwik.php'
    environment: dev
logging:
  level:
    de.tk.opensource.privacyproxy: DEBUG
---
spring:
  profiles: qa
assets:
  fileLocation: 'tmp/privacy-proxy'
example:
  scripts:
    endpoints:
      - remoteUrl: 'https://code.jquery.com/jquery-3.3.1.min.js'
        filename: 'jquery.js'
    interval: '0 */2 * * * ?'
  routing:
    endpoint: https://tracking.example.de/qa/piwik.php
    environment: qa
---
spring:
  profiles: prod
assets:
  fileLocation: 'tmp/privacy-proxy'
example:
  scripts:
    endpoints:
      - remoteUrl: 'https://code.jquery.com/jquery-3.3.1.min.js'
        filename: 'jquery.js'
    interval: '0 */30 * * * ?'
  routing:
    endpoint: 'https://tracking.example.de/prod/piwik.php'
    environment: prod
